### PR TITLE
Delete Setup.hs

### PR DESCRIPTION
**Pull request by jappeace**
It breaks with ghc 8.8.3. I don't think it does anything (correct me if I'm wrong).

### CODE REVIEW

**Comment by LaloHao** [comment]
Are you using Nix by chance? [I added some compiler flags ](https://github.com/LaloHao/binary-search/commit/4dfe1390ab1b9a12a09fbd14df020eac20faca24)and it seems to work both for old (ghc822) and new (>=ghc883)

I manually tested from ghc883 until ghc8102

This was the error i got

```hs
[1 of 1] Compiling Main             ( Setup.hs, /build/Main.o )

Setup.hs:2:29: error:
    Variable not in scope: defaultUserHooks :: UserHooks
  |
2 | main = defaultMainWithHooks defaultUserHooks
  |   
```

**Comment by jappeace** [comment]
@LaloHao yes exactly that:
```
[1 of 1] Compiling Main             ( Setup.hs, /build/Main.o )

Setup.hs:2:29: error:
    Variable not in scope: defaultUserHooks :: UserHooks
  |
2 | main = defaultMainWithHooks defaultUserHooks
  |                             ^^^^^^^^^^^^^^^^

```

I'm contacting the author now.

**Comment by jappeace** [comment]
Hmm, their email accounts are full according to gmail, I suppose I'll just ask hackage to take over maintainership

**Comment by jappeace** [comment]
So I can fix this within a mere 6 weeks! Or the author responds:

https://mail.haskell.org/pipermail/haskell-cafe/2021-January/133353.html

Either way it'll be fixed.

**Comment by noughtmare** [comment]
A proper cabal package does require a `Setup.hs` file. As described in [the cabal documentation](https://cabal.readthedocs.io/en/3.4/cabal-package.html#pkg-field-build-type), if the `build-type` is `Simple` then it must have the standardized content:

```Haskell
import Distribution.Simple
main = defaultMain
```

It seems like the current `Setup.hs` in this cabal package did not adhere to this and that caused you issues, but I think you should change it instead of simply throwing it away. Some Haskell workflows might expect a `Setup.hs` file to be present.

**Comment by jappeace** [comment]
Upstream is here now: https://github.com/riskbook/binary-search

I uploaded a new release on hackage as well

**Pull request closed without merging**
